# Generated by Django 5.1.1 on 2024-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('isdone', models.BooleanField(default=False)),
                ('untildate', models.DateField()),
            ],
        ),
    ]
